In [4]:
import numpy as np

In [7]:
arr = np.array([1,2,3])

In [8]:
print(arr)

[1 2 3]


In [9]:
print(arr.shape)

(3,)


In [10]:
print(arr.dtype)

int32


In [11]:
print(arr.size)

3


In [12]:
print(arr.itemsize)

4


In [13]:
print(arr.nbytes)

12


In [15]:
b = np.array([[1,2,3], [3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [16]:
b = b * 2
print(b)

[[ 2  4  6]
 [ 6  8 10]]


In [17]:
print(b.shape)

(2, 3)


In [21]:
# Get value
print(b[0,2])

6


In [23]:
# Get Row
print(b[0,:])

[2 4 6]


In [25]:
# Get Column
print(b[:,0])

[2 6]


In [29]:
print(b[1, 0:2])

[6 8]


In [30]:
# Sum
print(arr+5)

[6 7 8]


In [31]:
# Multiply
print(arr*5)

[ 5 10 15]


In [32]:
# Mean
print(arr.mean())

2.0


In [37]:
# Sum
print(np.sum(arr))

6


In [ ]:
print(np.sum(b)